### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by nsunami** [nsunami/postreview-app#41]
`Failed to compile.
./app/core/components/PopupReview.tsx:25:49
Type error: Property 'questionId' does not exist on type '{ displayName: string | null; review: (ReviewAnswers & { question: ReviewQuestions; })[]; id: number; handle: string; icon: string | null; }'.
  23 |   const updateRating = (questionId, newRating) => {
  24 |     const newAnswers = [...reviewAnswers]
> 25 |     const index = newAnswers.findIndex((r) => r.questionId === questionId)
     |                                                 ^
  26 |     if (index < 0) newAnswers[questionId - 1] = newRating
  27 |     if (index >= 0) newAnswers[index] = newRating
  28 |     setReviewAnswers(newAnswers)
`

**Comment by nsunami** [comment]
The root of the issue may be that the front-end questions are 6-point scale, whereas seeded questions are on a 5-point scale. I need to change the front end.

**Comment by nsunami** [comment]
Still failing with the following message:
```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/tmp/build_2055ef13/node_modules/next/dist/compiled/webpack/bundle5.js:133896:18)
    at BulkUpdateDecorator.update (/tmp/build_2055ef13/node_modules/next/dist/compiled/webpack/bundle5.js:133797:50)
    at /tmp/build_2055ef13/node_modules/next/dist/compiled/webpack/bundle5.js:54553:9
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v17.2.0
-----> Build failed
```

**Comment by nsunami** [comment]
Now the deployment is failing with the following message: 
```
1 migration found in prisma/migrations
Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
```

**Comment by nsunami** [comment]
Fixed by resetting the database on Heroku:
`heroku pg:reset`
